name: Prod Deploy (ArgoCD)

on:
  push:
    branches: [main]
    paths-ignore:
      - 'package.json'
      - 'package-lock.json'
  workflow_dispatch:
    inputs:
      bump-type:
        description: "Semver Bump Type"
        required: true
        type: choice
        options:
          - "patch"
          - "minor"
          - "major"

jobs:
  # lint:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Run linting
  #       uses: pablomarelli/homelab-workflows/.github/actions/lint/LANGUAGE@main
  #
  # test:
  #   runs-on: ubuntu-latest
  #   needs: lint
  #   steps:
  #     - name: Run tests
  #       uses: pablomarelli/homelab-workflows/.github/actions/test/LANGUAGE@main

  bump-version:
    if: ${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master' || github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.bump.outputs.version }}
    steps:
      - name: Bump version
        id: bump
        uses: pablomarelli/homelab-workflows/.github/actions/bump-version/LANGUAGE@main
        with:
          bump-type: ${{ inputs.bump-type || 'patch' }}
          token: ${{ secrets.REPOS_TOKEN }}

  build:
    runs-on: ubuntu-latest
    needs: bump-version
    permissions:
      contents: read
      packages: write
    steps:
      - name: Build and Push Docker image
        uses: pablomarelli/homelab-workflows/.github/actions/docker-build@main
        with:
          docker-registry: ghcr.io          
          docker-image: ${{ github.repository }}
          docker-username: ${{ github.actor }}
          docker-password: ${{ secrets.GITHUB_TOKEN }}
          docker-push: true
          version: ${{ needs.bump-version.outputs.version }}

  deploy:
    runs-on: ubuntu-latest
    needs: [bump-version, build]
    steps:
      - name: Deploy to ArgoCD
        uses: pablomarelli/homelab-workflows/.github/actions/argo-deploy@main
        with:
          app-name: ${{ github.event.repository.name }}
          environment: prod
          version: ${{ needs.bump-version.outputs.version }}
          token: ${{ secrets.INFRA_REPO_TOKEN }}
