name: 'Docker Build and Push'
description: 'Builds and pushes a Docker image to a registry'

inputs:
  docker-registry:
    description: 'Docker registry URL'
    required: true
    default: 'ghcr.io'
  docker-image:
    description: 'Name of the image (defaults to repo name)'
    required: true
  docker-username:
    description: 'Docker username'
    required: true
    default: ${{ github.actor }}
  docker-password:
    description: 'Docker password (GITHUB_TOKEN for ghcr.io)'
    required: true
  docker-push:
    description: 'Do we push the docker image'
    default: false
  version:
    description: 'Version tag for the image'
    required: false

outputs:
  image:
    description: 'Full image name with registry and tag'
    value: ${{ steps.meta.outputs.tags }}
  version:
    description: 'Version used for the image'
    value: ${{ steps.version.outputs.version }}

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

    - name: Log in to Docker Registry
      uses: docker/login-action@v2
      with:
        registry: ${{ inputs.docker-registry }}
        username: ${{ inputs.docker-username }}
        password: ${{ inputs.docker-password }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Extract image name
      id: imagename
      shell: bash
      run: |
        IMAGE_NAME="${{ inputs.docker-image }}"
        IMAGE_NAME=$(basename "$IMAGE_NAME")
        echo "image=$IMAGE_NAME" >> "$GITHUB_OUTPUT"

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ inputs.docker-registry }}/${{ steps.imagename.outputs.image }}
        tags: |
          type=sha,prefix=
          type=ref,event=branch
          type=ref,event=tag
          type=ref,event=pr
          type=raw,value=latest
          type=semver,pattern={{version}},value=${{ steps.version.outputs.version }},enable={{is_default_branch}}
          type=raw,value=${{ inputs.version }}

    - name: Show generated Docker tags
      run: | 
        echo "Tags: ${{ steps.meta.outputs.tags }}"
      shell: bash

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        platforms: linux/amd64
        push: ${{ inputs.docker-push }}
        tags: ${{ steps.meta.outputs.tags }}
        cache-from: type=registry,ref=${{ inputs.docker-registry }}/${{ steps.imagename.outputs.image }}:latest
        cache-to: type=registry,ref=${{ inputs.docker-registry }}/${{ steps.imagename.outputs.image }}:latest,mode=max
