name: 'Python Lint'
description: 'Runs linting on Python code using Ruff'

inputs:
  python-version:
    description: 'Python version to use'
    required: false
    default: '3.12.4'

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install Ruff
      shell: bash
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade ruff

    - name: Run Ruff
      shell: bash
      run: |
        ruff check .
